# Generated by Django 5.2.5 on 2025-09-01 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('property_type', models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy'), ('sell', 'Sell'), ('pg', 'PG')], max_length=20)),
                ('category', models.CharField(choices=[('room', 'Room'), ('flat', 'Flat'), ('plot', 'Plot'), ('commercial', 'Commercial')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='core.propertyaddress')),
            ],
        ),
        migrations.CreateModel(
            name='PGDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_gender', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('both', 'Both')], max_length=10)),
                ('room_type', models.CharField(choices=[('private', 'Private Room'), ('double', 'Double Sharing'), ('triple', 'Triple Sharing')], max_length=20)),
                ('wifi', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('housekeeping', models.BooleanField(default=False)),
                ('max_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pg_details', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.property')),
            ],
        ),
    ]
